image: ros:eloquent

build:
 stage: build
 script:
   - apt update
   - apt --yes --force-yes install qtwebengine5-dev libboost-dev ros-eloquent-rqt-gui-cpp ros-eloquent-interactive-markers
 
   - source /opt/ros/eloquent/setup.bash
   
   - mkdir -p ros_ws/src
   - cd ros_ws/src
   - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@spgit.informatik.uni-ulm.de/quadrocopter/quad_common_utils.git -b ros2
   - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@spgit.informatik.uni-ulm.de/quadrocopter/se_trajectory_msgs.git -b ros2
   - git clone https://github.com/sp-uulm/MiniLua.git
   - cd ../..
   
   - rm -f ros_ws/src/interactive_script || true
   - ln -s $(pwd) ros_ws/src/interactive_script
   
   - cd ros_ws
   - rm -rf build install log
   - colcon build --packages-up-to interactive_script
   - source install/local_setup.bash
 artifacts:
    paths:
        - ros_ws/install

