#!/usr/bin/env python3

import sys

from rqt_gui.main import Main


def add_arguments(parser):
    group = parser.add_argument_group('Options for interactive_script plugin')

main = Main()
sys.exit(main.main(
    sys.argv,
    standalone='interactive_script_plugin/InteractiveScriptGui',
    plugin_argument_provider=add_arguments))
